apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
  namespace: noodle-soup
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi